### ISSUE TITLE
python module ekleme

### ISSUE THREAD

**Issue by DeliDoktoru** [ismailg6/webBase#5]
kullanmış olduğumuz algoritmaları (örn:fibonacı) bir python dosyasında topluyalım sonra views.py den oluşturduğumuz python dosyasındaki fibonacci fonksiyonunu çağıralım böylelikle her python dosyası kendi üzerine düşen görevi yapıcak şekilde olmuş olur. 

          **Her yazılım biriminin (sınıf, nesne, metot) tek bir sorumluluğu olmalıdır.**
                                      **--SOLİD**

**Comment by ismailg6** [comment]
yapıldı amirim
