### ISSUE TITLE
404 sayfası

### ISSUE THREAD

**Issue by DeliDoktoru** [ismailg6/webBase#6]
var olmayan bir sayfayı görmek için istek attığımız olmadığını gösteren bir 404 sayfası fena olmaz

**Comment by ismailg6** [comment]
not found sayfası oluşturuldu fakat  djangonun oluşturduğu not found sayfası yerine kendi oluşturduğumu ayarlayamıyorum.internette gördüklerimi yaptığımda kendi oluşturduğum notfound.html sayfası düzgün çalışmıyor
