### ISSUE TITLE
tags ve filters

### ISSUE THREAD

**Issue by DeliDoktoru** [ismailg6/webBase#8]
Not bu issuesi yapmadan önce "bir listeyi ekrana yazdırmak" issuesini  yap

https://docs.djangoproject.com/en/2.0/ref/templates/builtins/ şu linkteki öğretilen şeyleri yeni bir web sayfasında herbirini alt alta test edecek şekilde yapalım ve unutmamak için herbirine ne yaptığını anlatan türkçe yorum satırları ekliyelim

**Comment by ismailg6** [comment]
zaman kaybetttim açıklamadaki değişkenlerin anlamsız gelmesi ve durmasından  atladım bu issueyu
